name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on:  windows-2019
    env:
      Solution_Name: Holos.sln
      Test_Project_Path: H.*.Test/*[tT]est.csproj # not used yet

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0        

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore nuget packages
      run: msbuild $env:Solution_Name /t:Restore
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build solution
      run: msbuild $env:Solution_Name /p:platform="Any CPU" /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Files-${{ matrix.configuration }}
        path: '**/*/bin/*'
